name       : kalzium
version    : 21.12.3
release    : 4
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/kalzium-21.12.3.tar.xz : 944a544512ca0830520d4d121bf661c323795390e3ac200b3abaa261600b0ae2
homepage   : https://apps.kde.org/kalzium/
license    : GPL-2.0-or-later
component  : desktop
summary    : Periodic Table of Elements
description: |
    Periodic Table of Elements
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdoctools-devel
    - kparts-devel
    - kplotting-devel
    - kunitconversion-devel
    - ocaml
    - eigen3
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
