name       : kalzium
version    : 22.04.3
release    : 8
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/kalzium-22.04.3.tar.xz : 46c0cce0caeb6de1ab60f294f7fb63790aa14427bf4c18be281e7ca31a983e40
homepage   : https://apps.kde.org/kalzium/
license    : GPL-2.0-or-later
component  : desktop
summary    : Periodic Table of Elements
description: |
    Periodic Table of Elements
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdoctools-devel
    - kparts-devel
    - kplotting-devel
    - kunitconversion-devel
    - ocaml
    - eigen3
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
