name       : kalzium
version    : 21.08.3
release    : 1
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kalzium-21.08.3.tar.xz : 7492761c9726b82795b97a1a6184281a0b8807b39b0baafaa7f7f3251cb0ed74
homepage   : https://apps.kde.org/kalzium/
license    : GPL-2.0-or-later
component  : desktop
summary    : Periodic Table of Elements
description: |
    Periodic Table of Elements
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdoctools-devel
    - kparts-devel
    - kplotting-devel
    - kunitconversion-devel
    - ocaml
    - eigen3
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
