name       : kalzium
version    : 22.04.0
release    : 5
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/kalzium-22.04.0.tar.xz : bbc13198d41f29c2ea399a8b4ab8f0f4c02f822250bb29079e4873ca68b3f41d
homepage   : https://apps.kde.org/kalzium/
license    : GPL-2.0-or-later
component  : desktop
summary    : Periodic Table of Elements
description: |
    Periodic Table of Elements
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdoctools-devel
    - kparts-devel
    - kplotting-devel
    - kunitconversion-devel
    - ocaml
    - eigen3
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
