name       : kalzium
version    : 22.04.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/kalzium-22.04.2.tar.xz : 0631d96b6a33aaf6c6baedabdde198d8f832f6bfd28db5610947c3160b2fce20
homepage   : https://apps.kde.org/kalzium/
license    : GPL-2.0-or-later
component  : desktop
summary    : Periodic Table of Elements
description: |
    Periodic Table of Elements
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdoctools-devel
    - kparts-devel
    - kplotting-devel
    - kunitconversion-devel
    - ocaml
    - eigen3
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
