name       : kalzium
version    : 21.12.0
release    : 2
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/kalzium-21.12.0.tar.xz : 07d1055296c5983efd2f7ec4e48ea6f30325b7504a1169a0377a545cd29f3612
homepage   : https://apps.kde.org/kalzium/
license    : GPL-2.0-or-later
component  : desktop
summary    : Periodic Table of Elements
description: |
    Periodic Table of Elements
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdoctools-devel
    - kparts-devel
    - kplotting-devel
    - kunitconversion-devel
    - ocaml
    - eigen3
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
