name       : kalzium
version    : 21.12.1
release    : 3
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/kalzium-21.12.1.tar.xz : 007e4128dad6e5c10ab7c64aed41f60c56029cef22f74a63a86ed78ac503a16b
homepage   : https://apps.kde.org/kalzium/
license    : GPL-2.0-or-later
component  : desktop
summary    : Periodic Table of Elements
description: |
    Periodic Table of Elements
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdoctools-devel
    - kparts-devel
    - kplotting-devel
    - kunitconversion-devel
    - ocaml
    - eigen3
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
