name       : kalzium
version    : 22.08.3
release    : 9
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kalzium-22.08.3.tar.xz : 0c743f7cef68ffca68605763ca740ed3a7fd26d0f085a80ad6b5f3b777ea5c50
homepage   : https://apps.kde.org/kalzium/
license    : GPL-2.0-or-later
component  : desktop
summary    : Periodic Table of Elements
description: |
    Periodic Table of Elements
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdoctools-devel
    - kparts-devel
    - kplotting-devel
    - kunitconversion-devel
    - ocaml
    - eigen3
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
