name       : kalzium
version    : 23.04.2
release    : 13
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/kalzium-23.04.2.tar.xz : 84940e86a4fd76451b0518a31f07c9aa621215ba5bcc4418ef867629dc0f8cd1
homepage   : https://apps.kde.org/kalzium/
license    : GPL-2.0-or-later
component  : desktop
summary    : Periodic Table of Elements
description: |
    Periodic Table of Elements
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdoctools-devel
    - kparts-devel
    - kplotting-devel
    - kunitconversion-devel
    - ocaml
    - eigen3
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
